version: '3.8'

services:
  redis:
    image: redis:alpine
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "6379:6379"

  main-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: ["nodemon", "src/index.js"]  # Використовуємо nodemon для автоматичного перезавантаження

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    deploy:
      replicas: 5  # Репліки воркерів для паралельної обробки
      restart_policy:
        condition: on-failure
    command: ["nodemon", "src/worker.js"]  # Використовуємо nodemon для автоматичного перезавантаження
