version: '3.8'

services:
  redis:
    image: redis:alpine
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "6379:6379"

  main-server:
    image: main-server:latest  # Використовуємо локально зібраний образ
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: ["node", "src/index.js"]

  worker:
    image: worker:latest  # Використовуємо локально зібраний образ
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    command: ["node", "src/worker.js"]
